apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }}-pvc
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 10Gi






      